# Generated by Django 3.2.5 on 2021-07-09 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_photo', models.ImageField(upload_to='categories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999, 'Incorrect Phone number.'), django.core.validators.MinValueValidator(1111111111, 'Incorrect Phone number.')])),
                ('profile_photo', models.ImageField(upload_to='laundries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laundry',
                'verbose_name_plural': 'Laundries',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('ld', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dc', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pr', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='laundry.category')),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='laundry.laundry')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='laundry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='laundry.laundry'),
        ),
    ]
