# Generated by Django 3.2.5 on 2021-07-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_auto_20210710_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='laundry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laundry.laundry'),
        ),
        migrations.AlterField(
            model_name='item',
            name='laundry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laundry.laundry'),
        ),
    ]
