# Generated by Django 3.2.5 on 2021-07-09 18:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_address', models.TextField(blank=True, max_length=500, null=True)),
                ('delivery_address', models.TextField(blank=True, max_length=500, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999, 'Incorrect Phone number.'), django.core.validators.MinValueValidator(1111111111, 'Incorrect Phone number.')])),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('delivered', 'delivered')], default='pending', max_length=20)),
                ('instructions', models.CharField(blank=True, max_length=200, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('bkash', 'bkash'), ('nagad', 'nagad'), ('rocket', 'rocket'), ('visa', 'visa'), ('mastercard', 'mastercard')], default='pending', max_length=20)),
                ('processing_date', models.DateField(blank=True, null=True)),
                ('cancel_date', models.DateField(blank=True, null=True)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
