# Generated by Django 3.2.5 on 2021-07-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
        ('order', '0003_auto_20210710_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItems',
        ),
    ]
