# Generated by Django 3.2.5 on 2021-07-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_orderitem_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='dc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='ld',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='pr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
